[
    hello ghost welcome back
    {
        "domain": ".grammarly.com",
        "expirationDate": 1725852740,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1.1.1586428675.1718076740"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1718897581,
        "hostOnly": false,
        "httpOnly": false,
        "name": "isGrammarlyUser",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1749828781.389865,
        "hostOnly": false,
        "httpOnly": true,
        "name": "grauth",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AABNrzd0xKnwNl2ns7zPi89JWhkB6ltVYVFAYEki3ghSSB9_7O8Wkn-JilTYLxNqpU8K-SocJRkd3q82"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1718296384.692668,
        "hostOnly": false,
        "httpOnly": true,
        "name": "redirect_location",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "eyJ0eXBlIjoiIiwibG9jYXRpb24iOiJodHRwczovL2FwcC5ncmFtbWFybHkuY29tLyJ9"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1749828781.39066,
        "hostOnly": false,
        "httpOnly": true,
        "name": "last_authn_event",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "a8d6d6e6-eece-4ccf-b801-0156917c2613"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1752852784.767773,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_CBK9K2ZWWE",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GS1.1.1718292768.76.1.1718292784.44.0.0"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1726068771,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_rdt_uuid",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1710185871169.d96d108d-a2dc-45c1-856d-c3511c7c0673"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1751903097.452391,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__q_state_SWP2vgTKwt4Sucin",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "eyJ1dWlkIjoiYTJiZjE0YWEtODM1NC00NjViLWE4YTItMGI2ODc3YjJhNGY1IiwiY29va2llRG9tYWluIjoiZ3JhbW1hcmx5LmNvbSJ9"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1749828787.231355,
        "hostOnly": false,
        "httpOnly": false,
        "name": "experiment_groups",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "fsrw_in_sidebar_allusers_enabled|extension_assistant_bundles_all_consumers_enabled|fsrw_in_assistant_all_consumers_enabled|extension_new_rich_text_fields_enabled|officeaddin_outcomes_ui_exp5_enabled1|gdocs_for_chrome_enabled|completions_beta_enabled|premium_ungating_renewal_notification_enabled|kaza_security_hub_enabled|quarantine_messages_enabled|small_hover_menus_existing_enabled|gb_snippets_csv_upload_enabled|grammarly_web_ukraine_logo_dapi_enabled|officeaddin_upgrade_state_exp2_enabled1|gb_in_editor_premium_Test1|gb_analytics_mvp_phase_one_enabled|wonderpass_enabled|apply_formatting_all_consumers_enabled|attention_score_card_premium_no_iid_enabled|ipm_extension_release_test_1|snippets_in_ws_gate_enabled|extension_assistant_experiment_all_consumers_enabled|extension_assistant_bundles_all_enabled|officeaddin_proofit_exp3_enabled|gdocs_for_all_firefox_enabled|shared_workspaces_enabled|gb_analytics_mvp_phase_one_30_day_enabled|auto_complete_correct_safari_enabled|fluid_gdocs_rollout_enabled|officeaddin_ue_exp3_enabled|safari_migration_inline_disabled_enabled|officeaddin_upgrade_state_exp1_enabled1|completions_release_enabled1|extension_assistant_all_consumers_enabled|fsrw_in_assistant_all_enabled|autocorrect_new_ui_v3|emogenie_beta_enabled|apply_formatting_all_enabled|shadow_dom_chrome_enabled|extension_assistant_experiment_all_enabled|gdocs_for_all_safari_enabled|extension_assistant_all_enabled|safari_migration_backup_notif1_enabled|auto_complete_correct_edge_enabled|takeaways_premium_enabled|realtime_proofit_external_rollout_enabled|safari_migration_popup_editor_disabled_enabled|safari_migration_inline_warning_enabled|gdocs_new_mapping_enabled|officeaddin_muted_alerts_exp2_enabled1|officeaddin_perf_exp3_enabled"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1746801396.365922,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ga_clientId",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "540335385.1710185871"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1749828768,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_clck",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "130qz9q%7C2%7Cfml%7C0%7C1531"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1749828781.390339,
        "hostOnly": false,
        "httpOnly": false,
        "name": "csrf-token",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AABNr8wYckpeA4LpOmFK7gFvcCEalHChzNaQmw"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1718379172,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_clsk",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1va33t4%7C1718292772310%7C2%7C0%7Cq.clarity.ms%2Fcollect"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1725938969,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_fbp",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "fb.1.1710185875164.1351204228"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1752852768.440147,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GA1.1.540335385.1710185871"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1749828772,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_pin_unauth",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "dWlkPU4yUmlPV1kzWldZdFpUWXpNQzAwTW1ZMExUZ3haVFF0TkdJME1HUTBZakUwT0RjNQ"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1752852771.598333,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_tq_id.TV-7281365481-1.3988",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "3a43ff5d7da71912.1710185873.0.1718292772.."
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1718379168,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_uetsid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "30364c90299a11ef9d69d719b4932ad0"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1751988768,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_uetvid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "d953a0c0dfde11eeb32d7d12d8689f22"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1718296384.693561,
        "hostOnly": false,
        "httpOnly": false,
        "name": "browser_info",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "CHROME:124:COMPUTER:SUPPORTED:FREEMIUM:LINUX:LINUX"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1718400784.693272,
        "hostOnly": false,
        "httpOnly": false,
        "name": "funnelType",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "free"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1749828781.390972,
        "hostOnly": false,
        "httpOnly": true,
        "name": "gac",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AABNpO6uOEHEi3ApgLa3p9RN7LBs1QQkazcoiHOi8hyLUQbrV-Tjls7fOnQs5NiMlPUkn-TT43dDPfCKQBwKXRhbi8ofAdA_FLhvkEdNQuCt5ZdRd8iwZxlXJAXDM3kUQQdxG--G-P1OuJU8TA4yOKlo0X0"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1744745867.135472,
        "hostOnly": false,
        "httpOnly": false,
        "name": "gnar_containerId",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "dgtw8ovf7ahi0282"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1730514275,
        "hostOnly": false,
        "httpOnly": false,
        "name": "OptanonAlertBoxClosed",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "2024-05-06T02:24:35.259Z"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1730514275,
        "hostOnly": false,
        "httpOnly": false,
        "name": "OptanonConsent",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "isGpcEnabled=0&datestamp=Mon+May+06+2024+07%3A54%3A35+GMT%2B0530+(India+Standard+Time)&version=202404.1.0&browserGpcFlag=0&isIABGlobal=false&hosts=&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0003%3A1%2CC0004%3A1&AwaitingReconsent=false&geolocation=IN%3BMH"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1720505707,
        "hostOnly": false,
        "httpOnly": false,
        "name": "premiumWelcomeAddedDoc",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".grammarly.com",
        "expirationDate": 1744745920.858915,
        "hostOnly": false,
        "httpOnly": true,
        "name": "tdi",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "oozyd2ej02vkjcdfl"
    }
]
